defaultSemverRangePrefix: ''

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  '@jest/core@*':
    dependencies:
      pretty-format: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
